version = 0.1
[nonlive]
[nonlive.deploy]
[nonlive.deploy.parameters]
stack_name = "helloworld-sam-api"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-552x7yqogkhm"
s3_prefix = "helloworld-sam-api"
region = "eu-central-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
